// Mocks generated by Mockito 5.4.6 from annotations
// in household_docs_app/test/services/persistent_file_service_migration_unit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:amplify_core/amplify_core.dart' as _i2;
import 'package:async/async.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAuthPluginInterface_0 extends _i1.SmartFake
    implements _i2.AuthPluginInterface {
  _FakeAuthPluginInterface_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSignUpResult_1 extends _i1.SmartFake implements _i2.SignUpResult {
  _FakeSignUpResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResendSignUpCodeResult_2 extends _i1.SmartFake
    implements _i2.ResendSignUpCodeResult {
  _FakeResendSignUpCodeResult_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSignInResult_3 extends _i1.SmartFake implements _i2.SignInResult {
  _FakeSignInResult_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSignOutResult_4 extends _i1.SmartFake implements _i2.SignOutResult {
  _FakeSignOutResult_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUpdatePasswordResult_5 extends _i1.SmartFake
    implements _i2.UpdatePasswordResult {
  _FakeUpdatePasswordResult_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResetPasswordResult_6 extends _i1.SmartFake
    implements _i2.ResetPasswordResult {
  _FakeResetPasswordResult_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthUser_7 extends _i1.SmartFake implements _i2.AuthUser {
  _FakeAuthUser_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthSession_8 extends _i1.SmartFake implements _i2.AuthSession {
  _FakeAuthSession_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUpdateUserAttributeResult_9 extends _i1.SmartFake
    implements _i2.UpdateUserAttributeResult {
  _FakeUpdateUserAttributeResult_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeConfirmUserAttributeResult_10 extends _i1.SmartFake
    implements _i2.ConfirmUserAttributeResult {
  _FakeConfirmUserAttributeResult_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSendUserAttributeVerificationCodeResult_11 extends _i1.SmartFake
    implements _i2.SendUserAttributeVerificationCodeResult {
  _FakeSendUserAttributeVerificationCodeResult_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTotpSetupDetails_12 extends _i1.SmartFake
    implements _i2.TotpSetupDetails {
  _FakeTotpSetupDetails_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthDevice_13 extends _i1.SmartFake implements _i2.AuthDevice {
  _FakeAuthDevice_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStoragePluginInterface_14 extends _i1.SmartFake
    implements _i2.StoragePluginInterface {
  _FakeStoragePluginInterface_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStorageListOperation_15<Request extends _i2.StorageListRequest,
        Result extends _i2.StorageListResult<_i2.StorageItem>>
    extends _i1.SmartFake implements _i2.StorageListOperation<Request, Result> {
  _FakeStorageListOperation_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStorageGetPropertiesOperation_16<
        Request extends _i2.StorageGetPropertiesRequest,
        Result extends _i2.StorageGetPropertiesResult<_i2.StorageItem>>
    extends _i1.SmartFake
    implements _i2.StorageGetPropertiesOperation<Request, Result> {
  _FakeStorageGetPropertiesOperation_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStorageGetUrlOperation_17<Request extends _i2.StorageGetUrlRequest,
        Result extends _i2.StorageGetUrlResult> extends _i1.SmartFake
    implements _i2.StorageGetUrlOperation<Request, Result> {
  _FakeStorageGetUrlOperation_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStorageDownloadDataOperation_18<
        Request extends _i2.StorageDownloadDataRequest,
        Result extends _i2.StorageDownloadDataResult<_i2.StorageItem>>
    extends _i1.SmartFake
    implements _i2.StorageDownloadDataOperation<Request, Result> {
  _FakeStorageDownloadDataOperation_18(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStorageDownloadFileOperation_19<
        Request extends _i2.StorageDownloadFileRequest,
        Result extends _i2.StorageDownloadFileResult<_i2.StorageItem>>
    extends _i1.SmartFake
    implements _i2.StorageDownloadFileOperation<Request, Result> {
  _FakeStorageDownloadFileOperation_19(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStorageUploadDataOperation_20<
        Request extends _i2.StorageUploadDataRequest,
        Result extends _i2.StorageUploadDataResult<_i2.StorageItem>> extends _i1
    .SmartFake implements _i2.StorageUploadDataOperation<Request, Result> {
  _FakeStorageUploadDataOperation_20(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStorageUploadFileOperation_21<
        Request extends _i2.StorageUploadFileRequest,
        Result extends _i2.StorageUploadFileResult<_i2.StorageItem>> extends _i1
    .SmartFake implements _i2.StorageUploadFileOperation<Request, Result> {
  _FakeStorageUploadFileOperation_21(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStorageCopyOperation_22<
        Request extends _i2.StorageCopyRequest<_i2.StorageItem>,
        Result extends _i2.StorageCopyResult<_i2.StorageItem>>
    extends _i1.SmartFake implements _i2.StorageCopyOperation<Request, Result> {
  _FakeStorageCopyOperation_22(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStorageRemoveOperation_23<Request extends _i2.StorageRemoveRequest,
        Result extends _i2.StorageRemoveResult<_i2.StorageItem>> extends _i1
    .SmartFake implements _i2.StorageRemoveOperation<Request, Result> {
  _FakeStorageRemoveOperation_23(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStorageRemoveManyOperation_24<
        Request extends _i2.StorageRemoveManyRequest,
        Result extends _i2.StorageRemoveManyResult<_i2.StorageItem, Object>>
    extends _i1.SmartFake
    implements _i2.StorageRemoveManyOperation<Request, Result> {
  _FakeStorageRemoveManyOperation_24(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSignInDetails_25 extends _i1.SmartFake implements _i2.SignInDetails {
  _FakeSignInDetails_25(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAWSFile_26 extends _i1.SmartFake implements _i2.AWSFile {
  _FakeAWSFile_26(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeChunkedStreamReader_27<T> extends _i1.SmartFake
    implements _i3.ChunkedStreamReader<T> {
  _FakeChunkedStreamReader_27(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthCategory].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthCategory extends _i1.Mock implements _i2.AuthCategory {
  MockAuthCategory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Category get category => (super.noSuchMethod(
        Invocation.getter(#category),
        returnValue: _i2.Category.analytics,
      ) as _i2.Category);

  @override
  Set<_i2.Category> get categoryDependencies => (super.noSuchMethod(
        Invocation.getter(#categoryDependencies),
        returnValue: <_i2.Category>{},
      ) as Set<_i2.Category>);

  @override
  List<_i2.AuthPluginInterface> get plugins => (super.noSuchMethod(
        Invocation.getter(#plugins),
        returnValue: <_i2.AuthPluginInterface>[],
      ) as List<_i2.AuthPluginInterface>);

  @override
  _i2.AuthPluginInterface get defaultPlugin => (super.noSuchMethod(
        Invocation.getter(#defaultPlugin),
        returnValue: _FakeAuthPluginInterface_0(
          this,
          Invocation.getter(#defaultPlugin),
        ),
      ) as _i2.AuthPluginInterface);

  @override
  Plugin getPlugin<Plugin extends _i2.AuthPluginInterface>(
          _i2.AuthPluginKey<Plugin>? pluginKey) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPlugin,
          [pluginKey],
        ),
        returnValue: _i4.dummyValue<Plugin>(
          this,
          Invocation.method(
            #getPlugin,
            [pluginKey],
          ),
        ),
      ) as Plugin);

  @override
  _i5.Future<_i2.SignUpResult> signUp({
    required String? username,
    required String? password,
    _i2.SignUpOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [],
          {
            #username: username,
            #password: password,
            #options: options,
          },
        ),
        returnValue: _i5.Future<_i2.SignUpResult>.value(_FakeSignUpResult_1(
          this,
          Invocation.method(
            #signUp,
            [],
            {
              #username: username,
              #password: password,
              #options: options,
            },
          ),
        )),
      ) as _i5.Future<_i2.SignUpResult>);

  @override
  _i5.Future<_i2.SignUpResult> confirmSignUp({
    required String? username,
    required String? confirmationCode,
    _i2.ConfirmSignUpOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #confirmSignUp,
          [],
          {
            #username: username,
            #confirmationCode: confirmationCode,
            #options: options,
          },
        ),
        returnValue: _i5.Future<_i2.SignUpResult>.value(_FakeSignUpResult_1(
          this,
          Invocation.method(
            #confirmSignUp,
            [],
            {
              #username: username,
              #confirmationCode: confirmationCode,
              #options: options,
            },
          ),
        )),
      ) as _i5.Future<_i2.SignUpResult>);

  @override
  _i5.Future<_i2.ResendSignUpCodeResult> resendSignUpCode({
    required String? username,
    _i2.ResendSignUpCodeOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #resendSignUpCode,
          [],
          {
            #username: username,
            #options: options,
          },
        ),
        returnValue: _i5.Future<_i2.ResendSignUpCodeResult>.value(
            _FakeResendSignUpCodeResult_2(
          this,
          Invocation.method(
            #resendSignUpCode,
            [],
            {
              #username: username,
              #options: options,
            },
          ),
        )),
      ) as _i5.Future<_i2.ResendSignUpCodeResult>);

  @override
  _i5.Future<_i2.SignInResult> signIn({
    required String? username,
    String? password,
    _i2.SignInOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signIn,
          [],
          {
            #username: username,
            #password: password,
            #options: options,
          },
        ),
        returnValue: _i5.Future<_i2.SignInResult>.value(_FakeSignInResult_3(
          this,
          Invocation.method(
            #signIn,
            [],
            {
              #username: username,
              #password: password,
              #options: options,
            },
          ),
        )),
      ) as _i5.Future<_i2.SignInResult>);

  @override
  _i5.Future<_i2.SignInResult> confirmSignIn({
    required String? confirmationValue,
    _i2.ConfirmSignInOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #confirmSignIn,
          [],
          {
            #confirmationValue: confirmationValue,
            #options: options,
          },
        ),
        returnValue: _i5.Future<_i2.SignInResult>.value(_FakeSignInResult_3(
          this,
          Invocation.method(
            #confirmSignIn,
            [],
            {
              #confirmationValue: confirmationValue,
              #options: options,
            },
          ),
        )),
      ) as _i5.Future<_i2.SignInResult>);

  @override
  _i5.Future<_i2.SignOutResult> signOut({_i2.SignOutOptions? options}) =>
      (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
          {#options: options},
        ),
        returnValue: _i5.Future<_i2.SignOutResult>.value(_FakeSignOutResult_4(
          this,
          Invocation.method(
            #signOut,
            [],
            {#options: options},
          ),
        )),
      ) as _i5.Future<_i2.SignOutResult>);

  @override
  _i5.Future<_i2.UpdatePasswordResult> updatePassword({
    required String? oldPassword,
    required String? newPassword,
    _i2.UpdatePasswordOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePassword,
          [],
          {
            #oldPassword: oldPassword,
            #newPassword: newPassword,
            #options: options,
          },
        ),
        returnValue: _i5.Future<_i2.UpdatePasswordResult>.value(
            _FakeUpdatePasswordResult_5(
          this,
          Invocation.method(
            #updatePassword,
            [],
            {
              #oldPassword: oldPassword,
              #newPassword: newPassword,
              #options: options,
            },
          ),
        )),
      ) as _i5.Future<_i2.UpdatePasswordResult>);

  @override
  _i5.Future<_i2.ResetPasswordResult> resetPassword({
    required String? username,
    _i2.ResetPasswordOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [],
          {
            #username: username,
            #options: options,
          },
        ),
        returnValue: _i5.Future<_i2.ResetPasswordResult>.value(
            _FakeResetPasswordResult_6(
          this,
          Invocation.method(
            #resetPassword,
            [],
            {
              #username: username,
              #options: options,
            },
          ),
        )),
      ) as _i5.Future<_i2.ResetPasswordResult>);

  @override
  _i5.Future<_i2.ResetPasswordResult> confirmResetPassword({
    required String? username,
    required String? newPassword,
    required String? confirmationCode,
    _i2.ConfirmResetPasswordOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #confirmResetPassword,
          [],
          {
            #username: username,
            #newPassword: newPassword,
            #confirmationCode: confirmationCode,
            #options: options,
          },
        ),
        returnValue: _i5.Future<_i2.ResetPasswordResult>.value(
            _FakeResetPasswordResult_6(
          this,
          Invocation.method(
            #confirmResetPassword,
            [],
            {
              #username: username,
              #newPassword: newPassword,
              #confirmationCode: confirmationCode,
              #options: options,
            },
          ),
        )),
      ) as _i5.Future<_i2.ResetPasswordResult>);

  @override
  _i5.Future<_i2.AuthUser> getCurrentUser(
          {_i2.GetCurrentUserOptions? options}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
          {#options: options},
        ),
        returnValue: _i5.Future<_i2.AuthUser>.value(_FakeAuthUser_7(
          this,
          Invocation.method(
            #getCurrentUser,
            [],
            {#options: options},
          ),
        )),
      ) as _i5.Future<_i2.AuthUser>);

  @override
  _i5.Future<List<_i2.AuthUserAttribute>> fetchUserAttributes(
          {_i2.FetchUserAttributesOptions? options}) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchUserAttributes,
          [],
          {#options: options},
        ),
        returnValue: _i5.Future<List<_i2.AuthUserAttribute>>.value(
            <_i2.AuthUserAttribute>[]),
      ) as _i5.Future<List<_i2.AuthUserAttribute>>);

  @override
  _i5.Future<_i2.AuthSession> fetchAuthSession(
          {_i2.FetchAuthSessionOptions? options}) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchAuthSession,
          [],
          {#options: options},
        ),
        returnValue: _i5.Future<_i2.AuthSession>.value(_FakeAuthSession_8(
          this,
          Invocation.method(
            #fetchAuthSession,
            [],
            {#options: options},
          ),
        )),
      ) as _i5.Future<_i2.AuthSession>);

  @override
  _i5.Future<_i2.SignInResult> signInWithWebUI({
    _i2.AuthProvider? provider,
    _i2.SignInWithWebUIOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithWebUI,
          [],
          {
            #provider: provider,
            #options: options,
          },
        ),
        returnValue: _i5.Future<_i2.SignInResult>.value(_FakeSignInResult_3(
          this,
          Invocation.method(
            #signInWithWebUI,
            [],
            {
              #provider: provider,
              #options: options,
            },
          ),
        )),
      ) as _i5.Future<_i2.SignInResult>);

  @override
  _i5.Future<_i2.UpdateUserAttributeResult> updateUserAttribute({
    required _i2.AuthUserAttributeKey? userAttributeKey,
    required String? value,
    _i2.UpdateUserAttributeOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserAttribute,
          [],
          {
            #userAttributeKey: userAttributeKey,
            #value: value,
            #options: options,
          },
        ),
        returnValue: _i5.Future<_i2.UpdateUserAttributeResult>.value(
            _FakeUpdateUserAttributeResult_9(
          this,
          Invocation.method(
            #updateUserAttribute,
            [],
            {
              #userAttributeKey: userAttributeKey,
              #value: value,
              #options: options,
            },
          ),
        )),
      ) as _i5.Future<_i2.UpdateUserAttributeResult>);

  @override
  _i5.Future<Map<_i2.AuthUserAttributeKey, _i2.UpdateUserAttributeResult>>
      updateUserAttributes({
    required List<_i2.AuthUserAttribute>? attributes,
    _i2.UpdateUserAttributesOptions? options,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #updateUserAttributes,
              [],
              {
                #attributes: attributes,
                #options: options,
              },
            ),
            returnValue: _i5.Future<
                    Map<_i2.AuthUserAttributeKey,
                        _i2.UpdateUserAttributeResult>>.value(
                <_i2.AuthUserAttributeKey, _i2.UpdateUserAttributeResult>{}),
          ) as _i5.Future<
              Map<_i2.AuthUserAttributeKey, _i2.UpdateUserAttributeResult>>);

  @override
  _i5.Future<_i2.ConfirmUserAttributeResult> confirmUserAttribute({
    required _i2.AuthUserAttributeKey? userAttributeKey,
    required String? confirmationCode,
    _i2.ConfirmUserAttributeOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #confirmUserAttribute,
          [],
          {
            #userAttributeKey: userAttributeKey,
            #confirmationCode: confirmationCode,
            #options: options,
          },
        ),
        returnValue: _i5.Future<_i2.ConfirmUserAttributeResult>.value(
            _FakeConfirmUserAttributeResult_10(
          this,
          Invocation.method(
            #confirmUserAttribute,
            [],
            {
              #userAttributeKey: userAttributeKey,
              #confirmationCode: confirmationCode,
              #options: options,
            },
          ),
        )),
      ) as _i5.Future<_i2.ConfirmUserAttributeResult>);

  @override
  _i5.Future<_i2.SendUserAttributeVerificationCodeResult>
      sendUserAttributeVerificationCode({
    required _i2.AuthUserAttributeKey? userAttributeKey,
    _i2.SendUserAttributeVerificationCodeOptions? options,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #sendUserAttributeVerificationCode,
              [],
              {
                #userAttributeKey: userAttributeKey,
                #options: options,
              },
            ),
            returnValue:
                _i5.Future<_i2.SendUserAttributeVerificationCodeResult>.value(
                    _FakeSendUserAttributeVerificationCodeResult_11(
              this,
              Invocation.method(
                #sendUserAttributeVerificationCode,
                [],
                {
                  #userAttributeKey: userAttributeKey,
                  #options: options,
                },
              ),
            )),
          ) as _i5.Future<_i2.SendUserAttributeVerificationCodeResult>);

  @override
  _i5.Future<_i2.TotpSetupDetails> setUpTotp({_i2.TotpSetupOptions? options}) =>
      (super.noSuchMethod(
        Invocation.method(
          #setUpTotp,
          [],
          {#options: options},
        ),
        returnValue:
            _i5.Future<_i2.TotpSetupDetails>.value(_FakeTotpSetupDetails_12(
          this,
          Invocation.method(
            #setUpTotp,
            [],
            {#options: options},
          ),
        )),
      ) as _i5.Future<_i2.TotpSetupDetails>);

  @override
  _i5.Future<void> verifyTotpSetup(
    String? totpCode, {
    _i2.VerifyTotpSetupOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyTotpSetup,
          [totpCode],
          {#options: options},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> rememberDevice() => (super.noSuchMethod(
        Invocation.method(
          #rememberDevice,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.AuthDevice> fetchCurrentDevice() => (super.noSuchMethod(
        Invocation.method(
          #fetchCurrentDevice,
          [],
        ),
        returnValue: _i5.Future<_i2.AuthDevice>.value(_FakeAuthDevice_13(
          this,
          Invocation.method(
            #fetchCurrentDevice,
            [],
          ),
        )),
      ) as _i5.Future<_i2.AuthDevice>);

  @override
  _i5.Future<void> forgetDevice([_i2.AuthDevice? device]) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgetDevice,
          [device],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i2.AuthDevice>> fetchDevices() => (super.noSuchMethod(
        Invocation.method(
          #fetchDevices,
          [],
        ),
        returnValue: _i5.Future<List<_i2.AuthDevice>>.value(<_i2.AuthDevice>[]),
      ) as _i5.Future<List<_i2.AuthDevice>>);

  @override
  _i5.Future<void> deleteUser() => (super.noSuchMethod(
        Invocation.method(
          #deleteUser,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> addPlugin(
    _i2.AuthPluginInterface? plugin, {
    required _i2.AmplifyAuthProviderRepository? authProviderRepo,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addPlugin,
          [plugin],
          {#authProviderRepo: authProviderRepo},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> reset() => (super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [StorageCategory].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageCategory extends _i1.Mock implements _i2.StorageCategory {
  MockStorageCategory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Category get category => (super.noSuchMethod(
        Invocation.getter(#category),
        returnValue: _i2.Category.analytics,
      ) as _i2.Category);

  @override
  Set<_i2.Category> get categoryDependencies => (super.noSuchMethod(
        Invocation.getter(#categoryDependencies),
        returnValue: <_i2.Category>{},
      ) as Set<_i2.Category>);

  @override
  List<_i2.StoragePluginInterface> get plugins => (super.noSuchMethod(
        Invocation.getter(#plugins),
        returnValue: <_i2.StoragePluginInterface>[],
      ) as List<_i2.StoragePluginInterface>);

  @override
  _i2.StoragePluginInterface get defaultPlugin => (super.noSuchMethod(
        Invocation.getter(#defaultPlugin),
        returnValue: _FakeStoragePluginInterface_14(
          this,
          Invocation.getter(#defaultPlugin),
        ),
      ) as _i2.StoragePluginInterface);

  @override
  P getPlugin<P extends _i2.StoragePluginInterface>(
          _i2.StoragePluginKey<P>? pluginKey) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPlugin,
          [pluginKey],
        ),
        returnValue: _i4.dummyValue<P>(
          this,
          Invocation.method(
            #getPlugin,
            [pluginKey],
          ),
        ),
      ) as P);

  @override
  _i2.StorageListOperation<_i2.StorageListRequest,
      _i2.StorageListResult<_i2.StorageItem>> list({
    required _i2.StoragePath? path,
    _i2.StorageListOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #list,
          [],
          {
            #path: path,
            #options: options,
          },
        ),
        returnValue: _FakeStorageListOperation_15<_i2.StorageListRequest,
            _i2.StorageListResult<_i2.StorageItem>>(
          this,
          Invocation.method(
            #list,
            [],
            {
              #path: path,
              #options: options,
            },
          ),
        ),
      ) as _i2.StorageListOperation<_i2.StorageListRequest,
          _i2.StorageListResult<_i2.StorageItem>>);

  @override
  _i2.StorageGetPropertiesOperation<_i2.StorageGetPropertiesRequest,
      _i2.StorageGetPropertiesResult<_i2.StorageItem>> getProperties({
    required _i2.StoragePath? path,
    _i2.StorageGetPropertiesOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProperties,
          [],
          {
            #path: path,
            #options: options,
          },
        ),
        returnValue: _FakeStorageGetPropertiesOperation_16<
            _i2.StorageGetPropertiesRequest,
            _i2.StorageGetPropertiesResult<_i2.StorageItem>>(
          this,
          Invocation.method(
            #getProperties,
            [],
            {
              #path: path,
              #options: options,
            },
          ),
        ),
      ) as _i2.StorageGetPropertiesOperation<_i2.StorageGetPropertiesRequest,
          _i2.StorageGetPropertiesResult<_i2.StorageItem>>);

  @override
  _i2.StorageGetUrlOperation<_i2.StorageGetUrlRequest, _i2.StorageGetUrlResult>
      getUrl({
    required _i2.StoragePath? path,
    _i2.StorageGetUrlOptions? options,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getUrl,
              [],
              {
                #path: path,
                #options: options,
              },
            ),
            returnValue: _FakeStorageGetUrlOperation_17<
                _i2.StorageGetUrlRequest, _i2.StorageGetUrlResult>(
              this,
              Invocation.method(
                #getUrl,
                [],
                {
                  #path: path,
                  #options: options,
                },
              ),
            ),
          ) as _i2.StorageGetUrlOperation<_i2.StorageGetUrlRequest,
              _i2.StorageGetUrlResult>);

  @override
  _i2.StorageDownloadDataOperation<_i2.StorageDownloadDataRequest,
      _i2.StorageDownloadDataResult<_i2.StorageItem>> downloadData({
    required _i2.StoragePath? path,
    void Function(_i2.StorageTransferProgress)? onProgress,
    _i2.StorageDownloadDataOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadData,
          [],
          {
            #path: path,
            #onProgress: onProgress,
            #options: options,
          },
        ),
        returnValue: _FakeStorageDownloadDataOperation_18<
            _i2.StorageDownloadDataRequest,
            _i2.StorageDownloadDataResult<_i2.StorageItem>>(
          this,
          Invocation.method(
            #downloadData,
            [],
            {
              #path: path,
              #onProgress: onProgress,
              #options: options,
            },
          ),
        ),
      ) as _i2.StorageDownloadDataOperation<_i2.StorageDownloadDataRequest,
          _i2.StorageDownloadDataResult<_i2.StorageItem>>);

  @override
  _i2.StorageDownloadFileOperation<_i2.StorageDownloadFileRequest,
      _i2.StorageDownloadFileResult<_i2.StorageItem>> downloadFile({
    required _i2.StoragePath? path,
    required _i2.AWSFile? localFile,
    void Function(_i2.StorageTransferProgress)? onProgress,
    _i2.StorageDownloadFileOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadFile,
          [],
          {
            #path: path,
            #localFile: localFile,
            #onProgress: onProgress,
            #options: options,
          },
        ),
        returnValue: _FakeStorageDownloadFileOperation_19<
            _i2.StorageDownloadFileRequest,
            _i2.StorageDownloadFileResult<_i2.StorageItem>>(
          this,
          Invocation.method(
            #downloadFile,
            [],
            {
              #path: path,
              #localFile: localFile,
              #onProgress: onProgress,
              #options: options,
            },
          ),
        ),
      ) as _i2.StorageDownloadFileOperation<_i2.StorageDownloadFileRequest,
          _i2.StorageDownloadFileResult<_i2.StorageItem>>);

  @override
  _i2.StorageUploadDataOperation<_i2.StorageUploadDataRequest,
      _i2.StorageUploadDataResult<_i2.StorageItem>> uploadData({
    required _i2.StorageDataPayload? data,
    required _i2.StoragePath? path,
    void Function(_i2.StorageTransferProgress)? onProgress,
    _i2.StorageUploadDataOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadData,
          [],
          {
            #data: data,
            #path: path,
            #onProgress: onProgress,
            #options: options,
          },
        ),
        returnValue: _FakeStorageUploadDataOperation_20<
            _i2.StorageUploadDataRequest,
            _i2.StorageUploadDataResult<_i2.StorageItem>>(
          this,
          Invocation.method(
            #uploadData,
            [],
            {
              #data: data,
              #path: path,
              #onProgress: onProgress,
              #options: options,
            },
          ),
        ),
      ) as _i2.StorageUploadDataOperation<_i2.StorageUploadDataRequest,
          _i2.StorageUploadDataResult<_i2.StorageItem>>);

  @override
  _i2.StorageUploadFileOperation<_i2.StorageUploadFileRequest,
      _i2.StorageUploadFileResult<_i2.StorageItem>> uploadFile({
    required _i2.AWSFile? localFile,
    required _i2.StoragePath? path,
    void Function(_i2.StorageTransferProgress)? onProgress,
    _i2.StorageUploadFileOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadFile,
          [],
          {
            #localFile: localFile,
            #path: path,
            #onProgress: onProgress,
            #options: options,
          },
        ),
        returnValue: _FakeStorageUploadFileOperation_21<
            _i2.StorageUploadFileRequest,
            _i2.StorageUploadFileResult<_i2.StorageItem>>(
          this,
          Invocation.method(
            #uploadFile,
            [],
            {
              #localFile: localFile,
              #path: path,
              #onProgress: onProgress,
              #options: options,
            },
          ),
        ),
      ) as _i2.StorageUploadFileOperation<_i2.StorageUploadFileRequest,
          _i2.StorageUploadFileResult<_i2.StorageItem>>);

  @override
  _i2.StorageCopyOperation<_i2.StorageCopyRequest<_i2.StorageItem>,
      _i2.StorageCopyResult<_i2.StorageItem>> copy({
    required _i2.StoragePath? source,
    required _i2.StoragePath? destination,
    _i2.StorageCopyOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #copy,
          [],
          {
            #source: source,
            #destination: destination,
            #options: options,
          },
        ),
        returnValue: _FakeStorageCopyOperation_22<
            _i2.StorageCopyRequest<_i2.StorageItem>,
            _i2.StorageCopyResult<_i2.StorageItem>>(
          this,
          Invocation.method(
            #copy,
            [],
            {
              #source: source,
              #destination: destination,
              #options: options,
            },
          ),
        ),
      ) as _i2.StorageCopyOperation<_i2.StorageCopyRequest<_i2.StorageItem>,
          _i2.StorageCopyResult<_i2.StorageItem>>);

  @override
  _i2.StorageRemoveOperation<_i2.StorageRemoveRequest,
      _i2.StorageRemoveResult<_i2.StorageItem>> remove({
    required _i2.StoragePath? path,
    _i2.StorageRemoveOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #remove,
          [],
          {
            #path: path,
            #options: options,
          },
        ),
        returnValue: _FakeStorageRemoveOperation_23<_i2.StorageRemoveRequest,
            _i2.StorageRemoveResult<_i2.StorageItem>>(
          this,
          Invocation.method(
            #remove,
            [],
            {
              #path: path,
              #options: options,
            },
          ),
        ),
      ) as _i2.StorageRemoveOperation<_i2.StorageRemoveRequest,
          _i2.StorageRemoveResult<_i2.StorageItem>>);

  @override
  _i2.StorageRemoveManyOperation<_i2.StorageRemoveManyRequest,
      _i2.StorageRemoveManyResult<_i2.StorageItem, Object>> removeMany({
    required List<_i2.StoragePath>? paths,
    _i2.StorageRemoveManyOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeMany,
          [],
          {
            #paths: paths,
            #options: options,
          },
        ),
        returnValue: _FakeStorageRemoveManyOperation_24<
            _i2.StorageRemoveManyRequest,
            _i2.StorageRemoveManyResult<_i2.StorageItem, Object>>(
          this,
          Invocation.method(
            #removeMany,
            [],
            {
              #paths: paths,
              #options: options,
            },
          ),
        ),
      ) as _i2.StorageRemoveManyOperation<_i2.StorageRemoveManyRequest,
          _i2.StorageRemoveManyResult<_i2.StorageItem, Object>>);

  @override
  _i5.Future<void> addPlugin(
    _i2.StoragePluginInterface? plugin, {
    required _i2.AmplifyAuthProviderRepository? authProviderRepo,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addPlugin,
          [plugin],
          {#authProviderRepo: authProviderRepo},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> reset() => (super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [AuthUser].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthUser extends _i1.Mock implements _i2.AuthUser {
  MockAuthUser() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get userId => (super.noSuchMethod(
        Invocation.getter(#userId),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#userId),
        ),
      ) as String);

  @override
  String get username => (super.noSuchMethod(
        Invocation.getter(#username),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#username),
        ),
      ) as String);

  @override
  _i2.SignInDetails get signInDetails => (super.noSuchMethod(
        Invocation.getter(#signInDetails),
        returnValue: _FakeSignInDetails_25(
          this,
          Invocation.getter(#signInDetails),
        ),
      ) as _i2.SignInDetails);

  @override
  String get runtimeTypeName => (super.noSuchMethod(
        Invocation.getter(#runtimeTypeName),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#runtimeTypeName),
        ),
      ) as String);

  @override
  Map<String, Object?> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, Object?>{},
      ) as Map<String, Object?>);
}

/// A class which mocks [StorageListResult].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageListResult<Item extends _i2.StorageItem> extends _i1.Mock
    implements _i2.StorageListResult<Item> {
  MockStorageListResult() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<Item> get items => (super.noSuchMethod(
        Invocation.getter(#items),
        returnValue: <Item>[],
      ) as List<Item>);

  @override
  bool get hasNextPage => (super.noSuchMethod(
        Invocation.getter(#hasNextPage),
        returnValue: false,
      ) as bool);
}

/// A class which mocks [StorageItem].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageItem extends _i1.Mock implements _i2.StorageItem {
  MockStorageItem() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get path => (super.noSuchMethod(
        Invocation.getter(#path),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#path),
        ),
      ) as String);

  @override
  Map<String, String> get metadata => (super.noSuchMethod(
        Invocation.getter(#metadata),
        returnValue: <String, String>{},
      ) as Map<String, String>);
}

/// A class which mocks [StorageGetPropertiesResult].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageGetPropertiesResult<Item extends _i2.StorageItem>
    extends _i1.Mock implements _i2.StorageGetPropertiesResult<Item> {
  MockStorageGetPropertiesResult() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Item get storageItem => (super.noSuchMethod(
        Invocation.getter(#storageItem),
        returnValue: _i4.dummyValue<Item>(
          this,
          Invocation.getter(#storageItem),
        ),
      ) as Item);
}

/// A class which mocks [StorageDownloadFileResult].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageDownloadFileResult<Item extends _i2.StorageItem>
    extends _i1.Mock implements _i2.StorageDownloadFileResult<Item> {
  MockStorageDownloadFileResult() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AWSFile get localFile => (super.noSuchMethod(
        Invocation.getter(#localFile),
        returnValue: _FakeAWSFile_26(
          this,
          Invocation.getter(#localFile),
        ),
      ) as _i2.AWSFile);

  @override
  Item get downloadedItem => (super.noSuchMethod(
        Invocation.getter(#downloadedItem),
        returnValue: _i4.dummyValue<Item>(
          this,
          Invocation.getter(#downloadedItem),
        ),
      ) as Item);
}

/// A class which mocks [StorageUploadFileResult].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageUploadFileResult<Item extends _i2.StorageItem> extends _i1.Mock
    implements _i2.StorageUploadFileResult<Item> {
  MockStorageUploadFileResult() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Item get uploadedItem => (super.noSuchMethod(
        Invocation.getter(#uploadedItem),
        returnValue: _i4.dummyValue<Item>(
          this,
          Invocation.getter(#uploadedItem),
        ),
      ) as Item);
}

/// A class which mocks [StorageRemoveResult].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageRemoveResult<Item extends _i2.StorageItem> extends _i1.Mock
    implements _i2.StorageRemoveResult<Item> {
  MockStorageRemoveResult() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Item get removedItem => (super.noSuchMethod(
        Invocation.getter(#removedItem),
        returnValue: _i4.dummyValue<Item>(
          this,
          Invocation.getter(#removedItem),
        ),
      ) as Item);
}

/// A class which mocks [AWSFile].
///
/// See the documentation for Mockito's code generation for more information.
class MockAWSFile extends _i1.Mock implements _i2.AWSFile {
  MockAWSFile() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<List<int>> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i5.Stream<List<int>>.empty(),
      ) as _i5.Stream<List<int>>);

  @override
  _i5.Future<int> get size => (super.noSuchMethod(
        Invocation.getter(#size),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<String?> get contentType => (super.noSuchMethod(
        Invocation.getter(#contentType),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i3.ChunkedStreamReader<int> getChunkedStreamReader() => (super.noSuchMethod(
        Invocation.method(
          #getChunkedStreamReader,
          [],
        ),
        returnValue: _FakeChunkedStreamReader_27<int>(
          this,
          Invocation.method(
            #getChunkedStreamReader,
            [],
          ),
        ),
      ) as _i3.ChunkedStreamReader<int>);

  @override
  _i5.Stream<List<int>> openRead([
    int? start,
    int? end,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #openRead,
          [
            start,
            end,
          ],
        ),
        returnValue: _i5.Stream<List<int>>.empty(),
      ) as _i5.Stream<List<int>>);
}
