// Mocks generated by Mockito 5.4.6 from annotations
// in household_docs_app/test/services/sync_state_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:household_docs_app/models/Document.dart' as _i6;
import 'package:household_docs_app/models/FileAttachment.dart' as _i7;
import 'package:household_docs_app/services/database_service.dart' as _i4;
import 'package:household_docs_app/services/log_service.dart' as _i8;
import 'package:household_docs_app/services/sync_identifier_service.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:sqflite/sqflite.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeValidationResult_1 extends _i1.SmartFake
    implements _i3.ValidationResult {
  _FakeValidationResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseService extends _i1.Mock implements _i4.DatabaseService {
  MockDatabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Database> get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _i5.Future<_i2.Database>.value(_FakeDatabase_0(
          this,
          Invocation.getter(#database),
        )),
      ) as _i5.Future<_i2.Database>);

  @override
  _i5.Future<int> createDocument(dynamic document) => (super.noSuchMethod(
        Invocation.method(
          #createDocument,
          [document],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> createDocumentWithLabels(
    _i6.Document? document,
    Map<String, String?>? fileLabels,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createDocumentWithLabels,
          [
            document,
            fileLabels,
          ],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<List<_i6.Document>> getAllDocuments([String? userId]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllDocuments,
          [userId],
        ),
        returnValue: _i5.Future<List<_i6.Document>>.value(<_i6.Document>[]),
      ) as _i5.Future<List<_i6.Document>>);

  @override
  _i5.Future<List<_i6.Document>> getDocumentsByCategory(
    String? category, [
    String? userId,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocumentsByCategory,
          [
            category,
            userId,
          ],
        ),
        returnValue: _i5.Future<List<_i6.Document>>.value(<_i6.Document>[]),
      ) as _i5.Future<List<_i6.Document>>);

  @override
  _i5.Future<List<_i6.Document>> getUserDocuments(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserDocuments,
          [userId],
        ),
        returnValue: _i5.Future<List<_i6.Document>>.value(<_i6.Document>[]),
      ) as _i5.Future<List<_i6.Document>>);

  @override
  _i5.Future<List<_i6.Document>> getUserDocumentsByCategory(
    String? userId,
    String? category,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserDocumentsByCategory,
          [
            userId,
            category,
          ],
        ),
        returnValue: _i5.Future<List<_i6.Document>>.value(<_i6.Document>[]),
      ) as _i5.Future<List<_i6.Document>>);

  @override
  _i5.Future<void> clearUserData(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #clearUserData,
          [userId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> clearAllData() => (super.noSuchMethod(
        Invocation.method(
          #clearAllData,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i6.Document>> getDocumentsPendingDeletion(
          [String? userId]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocumentsPendingDeletion,
          [userId],
        ),
        returnValue: _i5.Future<List<_i6.Document>>.value(<_i6.Document>[]),
      ) as _i5.Future<List<_i6.Document>>);

  @override
  _i5.Future<int> migrateDocumentsToUser(String? actualUserId) =>
      (super.noSuchMethod(
        Invocation.method(
          #migrateDocumentsToUser,
          [actualUserId],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> getPlaceholderDocumentCount() => (super.noSuchMethod(
        Invocation.method(
          #getPlaceholderDocumentCount,
          [],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<List<_i7.FileAttachment>> getFileAttachmentsWithLabels(
          int? documentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFileAttachmentsWithLabels,
          [documentId],
        ),
        returnValue:
            _i5.Future<List<_i7.FileAttachment>>.value(<_i7.FileAttachment>[]),
      ) as _i5.Future<List<_i7.FileAttachment>>);

  @override
  _i5.Future<void> addFileToDocument(
      syncId: SyncIdentifierService.generate(),

    int? documentId,
    String? filePath,
    String? label,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addFileToDocument,
          [
            documentId,
            filePath,
            label,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> addFileToDocumentBySyncId(
    String? syncId,
    String? filePath,
    String? label, {
    String? s3Key,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addFileToDocumentBySyncId,
          [
            syncId,
            filePath,
            label,
          ],
          {#s3Key: s3Key},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i7.FileAttachment>> getFileAttachmentsBySyncId(
          String? syncId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFileAttachmentsBySyncId,
          [syncId],
        ),
        returnValue:
            _i5.Future<List<_i7.FileAttachment>>.value(<_i7.FileAttachment>[]),
      ) as _i5.Future<List<_i7.FileAttachment>>);

  @override
  _i5.Future<int> updateFileLabel(
    int? documentId,
    String? filePath,
    String? label,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateFileLabel,
          [
            documentId,
            filePath,
            label,
          ],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> updateFilePathInAttachments(
    int? documentId,
    String? oldFilePath,
    String? newFilePath,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateFilePathInAttachments,
          [
            documentId,
            oldFilePath,
            newFilePath,
          ],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<void> removeFileFromDocument(
      syncId: SyncIdentifierService.generate(),

    int? documentId,
    String? filePath,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFileFromDocument,
          [
            documentId,
            filePath,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> replaceFileAttachmentsForDocument(
      syncId: SyncIdentifierService.generate(),

    int? documentId,
    List<_i7.FileAttachment>? attachments,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceFileAttachmentsForDocument,
          [
            documentId,
            attachments,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<int> updateDocument(dynamic document) => (super.noSuchMethod(
        Invocation.method(
          #updateDocument,
          [document],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> deleteDocument(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteDocument,
          [id],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<void> createTombstone(
    String? syncId,
    String? userId,
    String? deletedBy, {
    String? reason = 'user',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createTombstone,
          [
            syncId,
            userId,
            deletedBy,
          ],
          {#reason: reason},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> isTombstoned(String? syncId) => (super.noSuchMethod(
        Invocation.method(
          #isTombstoned,
          [syncId],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getTombstones(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTombstones,
          [userId],
        ),
        returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<int> cleanupOldTombstones() => (super.noSuchMethod(
        Invocation.method(
          #cleanupOldTombstones,
          [],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<_i6.Document?> getDocumentBySyncId(
    String? syncId, [
    String? userId,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocumentBySyncId,
          [
            syncId,
            userId,
          ],
        ),
        returnValue: _i5.Future<_i6.Document?>.value(),
      ) as _i5.Future<_i6.Document?>);

  @override
  _i5.Future<int> updateDocumentSyncId(
    int? documentId,
    String? syncId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDocumentSyncId,
          [
            documentId,
            syncId,
          ],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<List<_i6.Document>> getDocumentsWithoutSyncId([String? userId]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocumentsWithoutSyncId,
          [userId],
        ),
        returnValue: _i5.Future<List<_i6.Document>>.value(<_i6.Document>[]),
      ) as _i5.Future<List<_i6.Document>>);

  @override
  _i5.Future<int> updateFileAttachmentSyncId(
    int? attachmentId,
    String? syncId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateFileAttachmentSyncId,
          [
            attachmentId,
            syncId,
          ],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<dynamic> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);

  @override
  _i5.Future<bool> hasDuplicateSyncId(
    String? syncId,
    String? userId, {
    int? excludeDocumentId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #hasDuplicateSyncId,
          [
            syncId,
            userId,
          ],
          {#excludeDocumentId: excludeDocumentId},
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<List<String>> getUserSyncIds(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserSyncIds,
          [userId],
        ),
        returnValue: _i5.Future<List<String>>.value(<String>[]),
      ) as _i5.Future<List<String>>);

  @override
  _i5.Future<_i3.ValidationResult> validateUserSyncIds(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateUserSyncIds,
          [userId],
        ),
        returnValue:
            _i5.Future<_i3.ValidationResult>.value(_FakeValidationResult_1(
          this,
          Invocation.method(
            #validateUserSyncIds,
            [userId],
          ),
        )),
      ) as _i5.Future<_i3.ValidationResult>);
}

/// A class which mocks [LogService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogService extends _i1.Mock implements _i8.LogService {
  MockLogService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void log(
    String? message, {
    _i8.LogLevel? level = _i8.LogLevel.info,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #log,
          [message],
          {#level: level},
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i8.LogEntry> getAllLogs() => (super.noSuchMethod(
        Invocation.method(
          #getAllLogs,
          [],
        ),
        returnValue: <_i8.LogEntry>[],
      ) as List<_i8.LogEntry>);

  @override
  List<_i8.LogEntry> getLogsByLevel(_i8.LogLevel? level) => (super.noSuchMethod(
        Invocation.method(
          #getLogsByLevel,
          [level],
        ),
        returnValue: <_i8.LogEntry>[],
      ) as List<_i8.LogEntry>);

  @override
  void clearLogs() => super.noSuchMethod(
        Invocation.method(
          #clearLogs,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  String getLogsAsString() => (super.noSuchMethod(
        Invocation.method(
          #getLogsAsString,
          [],
        ),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.method(
            #getLogsAsString,
            [],
          ),
        ),
      ) as String);
}
